/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programming_Proyect_Swing;

import Classes.Persona;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC 2
 */
public class Ventana_Buscar_Data extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Buscar_Data
     */
    public Ventana_Buscar_Data() {
        initComponents();
        this.setSize(445, 375);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Busqueda = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombre_op = new javax.swing.JRadioButton();
        Codigo_op = new javax.swing.JRadioButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda");
        getContentPane().setLayout(null);

        Busqueda.setBackground(new java.awt.Color(153, 204, 0));
        Busqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Busqueda.setText("Buscar Registro");
        Busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(Busqueda);
        Busqueda.setBounds(140, 240, 150, 30);

        Cancelar.setBackground(new java.awt.Color(204, 153, 0));
        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar.setText("Cerrar Ventana");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(140, 290, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagen3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 230, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagen4.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 230, 100, 100);

        Dato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Dato);
        Dato.setBounds(80, 160, 290, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Busqueda por:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 90, 150, 20);

        buttonGroup1.add(Nombre_op);
        Nombre_op.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nombre_op.setText("Nombre Completo");
        getContentPane().add(Nombre_op);
        Nombre_op.setBounds(100, 120, 160, 23);

        buttonGroup1.add(Codigo_op);
        Codigo_op.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Codigo_op.setText("Código");
        getContentPane().add(Codigo_op);
        Codigo_op.setBounds(270, 120, 93, 23);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo2.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 430, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaActionPerformed
        if (Dato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar el formulario", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            LinkedList<Persona> buscado = buscarPersona();
            if (buscado == null) {
                JOptionPane.showMessageDialog(null, "No se encontró ningún resultado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                Ventana_Buscar vb = new Ventana_Buscar();
                vb.p = buscado.getFirst();
                vb.setVisible(true);
                vb.obtenerDatos();
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_BusquedaActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.setVisible(false);
        Ventana_Principal v = new Ventana_Principal();
        v.setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Buscar_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Buscar_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Buscar_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Buscar_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Buscar_Data().setVisible(true);
            }
        });
    }

    public LinkedList<Persona> buscarPersona() {
        int pos = -1;
        String dato = Dato.getText();
        LinkedList<Persona> search_result = new LinkedList<>();

        if (Nombre_op.isSelected() == true) {
            for (Persona p : Ventana_Agregar.Lista) {
                if (p.getNombre().equalsIgnoreCase(dato)) {
                    pos = Ventana_Agregar.Lista.indexOf(p);
                    search_result.add(Ventana_Agregar.Lista.get(pos));
                }
            }

            if (pos == -1) {
                search_result = null;
            }
        }

        if (Codigo_op.isSelected() == true) {
            for (Persona p : Ventana_Agregar.Lista) {
                if (p.getCodigo().equalsIgnoreCase(dato)) {
                    pos = Ventana_Agregar.Lista.indexOf(p);
                    search_result.add(Ventana_Agregar.Lista.get(pos));
                }
            }

            if (pos == -1) {
                search_result = null;
            }
        }

        return search_result;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busqueda;
    private javax.swing.JButton Cancelar;
    private javax.swing.JRadioButton Codigo_op;
    private javax.swing.JTextField Dato;
    private javax.swing.JLabel Fondo;
    private javax.swing.JRadioButton Nombre_op;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
