/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programming_Proyect_Swing;

import Classes.Persona;
import java.text.DecimalFormat;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author PC 2
 */
public class Ventana_Mostrar extends javax.swing.JFrame {

    DefaultTableModel model;
    String data[][] = {};
    String header[] = {"Código", "Nombre Completo", "Edad", "Consola", "Precio", "Fecha de Adquisición"};

    public Ventana_Mostrar() {
        initComponents();
        this.setSize(1000, 625);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        ((DefaultTableCellRenderer) Tabla_Personas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.RIGHT);

        Tabla_Personas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        Tabla_Personas.doLayout();

        model = new DefaultTableModel(data, header);
        Tabla_Personas.setModel(model);
        startTable();
    }

    public void startTable() {
        Tabla_Personas.removeAll();
        model.setRowCount(0);
        tableGenerator(Ventana_Agregar.Lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Banner = new javax.swing.JLabel();
        Opcion = new javax.swing.JComboBox<>();
        Dato_Buscar = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Personas = new javax.swing.JTable();
        End = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar Registros");
        getContentPane().setLayout(null);

        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner.png"))); // NOI18N
        getContentPane().add(Banner);
        Banner.setBounds(0, 0, 1000, 120);

        Opcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Completo", "Código de Registro" }));
        getContentPane().add(Opcion);
        Opcion.setBounds(170, 150, 150, 30);

        Dato_Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dato_Buscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Dato_Buscar);
        Dato_Buscar.setBounds(350, 150, 300, 30);

        Buscar.setBackground(new java.awt.Color(153, 153, 0));
        Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar);
        Buscar.setBounds(680, 150, 100, 30);

        Tabla_Personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Personas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 260, 810, 260);

        End.setBackground(new java.awt.Color(153, 102, 0));
        End.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        End.setText("Volver al menú");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        getContentPane().add(End);
        End.setBounds(440, 540, 123, 40);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (Dato_Buscar.getText().isEmpty()) {
            startTable();
        } else {
            LinkedList<Persona> buscado = buscarPersona();
            if (buscado == null) {
                JOptionPane.showMessageDialog(null, "No se encontró ningún resultado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                startSearchTable(buscado);
            }
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        this.setVisible(false);
        Ventana_Principal v = new Ventana_Principal();
        v.setVisible(true);
    }//GEN-LAST:event_EndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Mostrar().setVisible(true);
            }
        });
    }

    public void startSearchTable(LinkedList<Persona> e) {
        Tabla_Personas.removeAll();
        model.setRowCount(0);
        tableGenerator(e);
    }

    public LinkedList<Persona> buscarPersona() {
        int pos = -1, op = Opcion.getSelectedIndex();
        String dato = Dato_Buscar.getText();
        LinkedList<Persona> search_result = new LinkedList<>();

        switch (op) {
            case 0:
                for (Persona p : Ventana_Agregar.Lista) {
                    if (p.getNombre().equalsIgnoreCase(dato)) {
                        pos = Ventana_Agregar.Lista.indexOf(p);
                        search_result.add(Ventana_Agregar.Lista.get(pos));
                    }
                }
                if (pos == -1) {
                    search_result = null;
                }
                break;

            case 1:
                for (Persona p : Ventana_Agregar.Lista) {
                    if (p.getCodigo().equalsIgnoreCase(dato)) {
                        pos = Ventana_Agregar.Lista.indexOf(p);
                        search_result.add(Ventana_Agregar.Lista.get(pos));
                    }
                }
                if (pos == -1) {
                    search_result = null;
                }
                break;
        }
        return search_result;
    }
    
    public void tableGenerator(LinkedList<Persona> empleado) {

        DecimalFormat decimales = new DecimalFormat("0.00");

        for (Persona p : empleado) {

            String codigo, nombre, edad, consola, precio, fecha;

            codigo = p.getCodigo();
            nombre = p.getNombre();
            edad = String.valueOf(p.getEdad());
            consola = p.getConsola();
            precio = String.valueOf(decimales.format(p.getPrecio()));
            fecha = p.getFecha();

            String datas[] = {codigo, nombre, edad, consola, precio, fecha};
            model.addRow(datas);
            
            ((DefaultTableCellRenderer) Tabla_Personas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            
            TableColumnModel columnModel = Tabla_Personas.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(100);
            columnModel.getColumn(1).setPreferredWidth(250);
            columnModel.getColumn(2).setPreferredWidth(90);
            columnModel.getColumn(3).setPreferredWidth(180);
            columnModel.getColumn(4).setPreferredWidth(110);
            columnModel.getColumn(5).setPreferredWidth(150);

            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            Tabla_Personas.getColumnModel().getColumn(0).setCellRenderer(tcr);
            Tabla_Personas.getColumnModel().getColumn(1).setCellRenderer(tcr);
            Tabla_Personas.getColumnModel().getColumn(2).setCellRenderer(tcr);
            Tabla_Personas.getColumnModel().getColumn(3).setCellRenderer(tcr);
            Tabla_Personas.getColumnModel().getColumn(4).setCellRenderer(tcr);
            Tabla_Personas.getColumnModel().getColumn(5).setCellRenderer(tcr);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Dato_Buscar;
    private javax.swing.JButton End;
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> Opcion;
    private javax.swing.JTable Tabla_Personas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
