/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programming_Proyect_Swing;

import Classes.Persona;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.InputMismatchException;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC 2
 */
public class Ventana_Agregar extends javax.swing.JFrame {
    
    public static LinkedList<Persona> Lista = new LinkedList<Persona>();
    public static Persona persona;
    
    String nombre;
    int edad;
    String consola;
    double precio;
    String fecha;
    String comentario;
    String codigo;
    boolean e1 = false, e2 = false, e3 = false, e4 = false, e5 = false, e6 = false, e7 = false;
    
    public Ventana_Agregar() {
        initComponents();
        this.setSize(450, 555);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        Edad = new javax.swing.JFormattedTextField();
        Consola = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Comentario = new javax.swing.JTextArea();
        Cancelar = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Registro");
        setResizable(false);
        getContentPane().setLayout(null);

        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner1.png"))); // NOI18N
        getContentPane().add(Banner);
        Banner.setBounds(0, 0, 450, 90);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 400, 50, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 110, 68, 29);

        Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Nombre);
        Nombre.setBounds(130, 110, 260, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Consola:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 60, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Edad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 60, 29);

        Fecha.setDateFormatString("dd/MM/yyyy");
        Fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Fecha);
        Fecha.setBounds(130, 260, 260, 30);

        try {
            Edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Edad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Edad);
        Edad.setBounds(130, 210, 260, 30);

        Consola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Consola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Consola);
        Consola.setBounds(130, 160, 260, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 50, 29);

        Comentario.setColumns(20);
        Comentario.setRows(5);
        jScrollPane1.setViewportView(Comentario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 310, 260, 70);

        Cancelar.setBackground(new java.awt.Color(204, 153, 0));
        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(250, 460, 120, 40);

        Registrar.setBackground(new java.awt.Color(153, 204, 0));
        Registrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar);
        Registrar.setBounds(70, 460, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Comentario:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 330, 90, 29);

        Codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Codigo);
        Codigo.setBounds(300, 400, 120, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precio:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 400, 60, 29);

        Precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Precio);
        Precio.setBounds(100, 400, 120, 29);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo1.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 450, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.setVisible(false);
        Ventana_Principal v = new Ventana_Principal();
        v.setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        try {
            if (Nombre.getText().isEmpty()) {
                e1 = true;
                throw new NullPointerException();
            } else {
                nombre = Nombre.getText();
            }
            if (Consola.getText().isEmpty()) {
                e2 = true;
                throw new NullPointerException();
            } else {
                consola = Consola.getText();
            }
            if (Edad.getText().isEmpty()) {
                e3 = true;
                throw new NullPointerException();
            } else {
                edad = Integer.parseInt(Edad.getText());
            }
            if (Fecha.getDate() == null) {
                e4 = true;
                throw new NullPointerException();
            } else {
                Date f1 = Fecha.getDate();
                DateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                fecha = f.format(f1);
            }
            if (Comentario.getText().isEmpty()) {
                e5 = true;
                throw new NullPointerException();
            } else {
                comentario = Comentario.getText();
            }
            if (Precio.getText().isEmpty()) {
                e6 = true;
                throw new NullPointerException();
            } else {
                try {
                    precio = Double.parseDouble(Precio.getText());
                } catch (InputMismatchException e) {
                    e6 = true;
                }
            }
            if (Codigo.getText().isEmpty()) {
                e7 = true;
                throw new NullPointerException();
            } else {
                codigo = Codigo.getText();
            }
            
            persona = new Persona(nombre, edad, consola, precio, fecha, comentario, codigo);
            Lista.add(persona);
            
            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Personas.dat"));
                oos.writeObject(Lista);
                oos.close();
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                Ventana_Principal v = new Ventana_Principal();
                v.setVisible(true);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (InputMismatchException | NumberFormatException | NullPointerException e) {
            if (e1 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir el nombre completo del cliente");
                e1 = false;
            }
            if (e2 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir el nombre de la videoconsola vendida");
                e2 = false;
            }
            if (e3 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir la edad del cliente");
                e3 = false;
            }
            if (e4 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir la fecha de venta");
                e4 = false;
            }
            if (e5 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir un comentario del cliente");
                e5 = false;
            }
            if (e6 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir un precio valido");
                e6 = false;
            }
            if (e7 == true) {
                JOptionPane.showMessageDialog(this, "Debe escribir el codigo de registro");
                e7 = false;
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextArea Comentario;
    private javax.swing.JTextField Consola;
    private javax.swing.JFormattedTextField Edad;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Precio;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
